version: "3.8"

services:
  db:
    image: postgres:17.4
    container_name: postgres_barber
    restart: always
    environment:
      POSTGRES_USER: ${USER_POSTGRE}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
      POSTGRES_DB: ${USER_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - barber_net

  backend:
    build: .
    container_name: barber_backend
    command: npm run dev
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - barber_net
    
volumes:
  pgdata:

networks:
  barber_net:
