version: "3.8"

services:
  db:
    image: postgres:17.4
    container_name: postgres_barber
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14112003
      POSTGRES_DB: barberdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: .
    container_name: barber_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:14112003@db:5432/barberdb
      JWT_SECRET: chavesecretaprapensardepois

volumes:
  pgdata:
